version: "3.9"
services:
  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - mittNetwork

  app:
    build: ./app
    restart: always
#    links:
#      - db
    ports:
      - "5000:5000"
    depends_on:
      - "db"
    networks:
      - mittNetwork

networks:
  mittNetwork:
